{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import rospy as rp\n",
    "import jupyros as jr\n",
    "import math"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from geometry_msgs.msg import Pose, Vector3\n",
    "from sensor_msgs.msg import PointCloud2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "rp.init_node('runner')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "UsageError: Cell magic `%%thread_cell` not found.\n"
     ]
    }
   ],
   "source": [
    "%%thread_cell\n",
    "from geometry_msgs.msg import Pose, Vector3, \n",
    "import rospy as rp\n",
    "import math\n",
    "i = 0\n",
    "rate = rp.Rate(5)\n",
    "pub = rp.Publisher('/poser', Vector3, queue_size=10)\n",
    "while True:\n",
    "    msg = Vector3()\n",
    "    msg.x = math.sin(i * 0.1)\n",
    "    msg.y = math.cos(i * 0.1)\n",
    "    pub.publish(msg)\n",
    "    i += 1\n",
    "    rate.sleep()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "1cf813f0fb584a2c8adfb6baadca50a4",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "VBox(children=(HBox(children=(Button(description='Stop', style=ButtonStyle()),)), Output(layout=Layout(border=…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "jr.subscribe('/ti_mmwave/radar_scan_pcl', PointCloud2, lambda msg: print(msg))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "plot_string = '/ti_mmwave/radar_scan_pcl'\n",
    "topic = plot_string[:plot_string.find(':') - 1]\n",
    "fields = plot_string.split(':')[1:]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "78ececcd5996483a882cf27a1246254f",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Figure(axes=[Axis(label='X', scale=LinearScale()), Axis(label='Y', orientation='vertical', scale=LinearScale()…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1557517099.677199]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517099.706030]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517099.740076]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517099.770766]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517099.805433]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517099.840902]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517099.874908]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517099.905276]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517099.940266]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517099.975831]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.005302]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.040490]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.075571]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.105131]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.140365]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.174881]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.205006]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.240001]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.275351]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.304870]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.341078]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1557517100.370744]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.404786]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.440510]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.471116]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.505734]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.540782]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.575663]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.605095]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.641709]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.671707]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.704943]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.742805]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.776143]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.806437]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.842044]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.875682]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.906925]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.940792]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517100.977014]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.006965]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1557517101.040357]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.076485]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.105736]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.140549]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.175408]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.205471]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.241180]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.276440]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.305930]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.340954]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.375822]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.404605]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.440658]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.476185]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.506640]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.540863]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.575516]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.606071]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.640358]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.675006]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.705530]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1557517101.740690]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.776005]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.806746]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.840520]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.876018]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.905538]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.940303]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517101.976137]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.005954]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.040986]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.075863]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.105729]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.140873]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.175467]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.205680]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.240830]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.276099]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.306224]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.330043]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.377412]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.404900]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1557517102.440502]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.476915]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.506338]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.542053]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.576168]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.606675]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.642351]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.676847]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.721014]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.741845]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.775727]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.806788]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.850218]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.877614]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.906140]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.941530]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517102.977081]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.005989]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.041525]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1557517103.077081]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.107028]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.141898]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.184905]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.228990]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.241659]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.276712]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.306411]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.341944]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.377623]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.420950]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.441684]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.484936]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.497340]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.542186]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.577374]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.606901]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.642753]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.665264]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.712013]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.741674]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1557517103.777512]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.811689]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.830425]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.877814]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.921050]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.930809]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.976877]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517103.997011]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.043011]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.078018]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.108280]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.142908]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.164286]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.212502]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.254104]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.263999]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.313000]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.331963]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.377633]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.395728]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1557517104.443129]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.463588]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.497167]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.530811]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.564347]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.606217]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.641881]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.689038]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.707447]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.753068]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.776763]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.810360]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.831724]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.878418]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.897136]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.945149]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517104.964004]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.013120]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.056956]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.064357]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1557517105.106149]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.150254]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.196826]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.198789]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.232127]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.274075]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.318308]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.331851]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.374269]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.395848]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.431082]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.465288]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.498984]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.542095]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.566483]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.597729]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.631458]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.664223]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.696817]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.731412]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1557517105.764003]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.800029]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.842296]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.863880]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.912472]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.941181]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517105.976634]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.020821]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.041565]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.088849]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.106072]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.140616]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.175466]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.205785]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.252887]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.296865]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.305870]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.348993]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.376220]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1557517106.417930]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.440918]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.476144]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.506486]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.542152]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.570369]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.605994]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.640807]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.671292]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.705859]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.740965]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.771170]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.805974]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n",
      "[ERROR] [1557517106.841045]: bad callback: <function live_plot.<locals>.cb at 0x7ff813f257b8>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/home/tomek/.local/lib/python3.6/site-packages/jupyros/ros_widgets.py\", line 139, in cb\n",
      "    data_el.append(getattr(msg, f))\n",
      "AttributeError: 'PointCloud2' object has no attribute 'data.x'\n",
      "\n"
     ]
    }
   ],
   "source": [
    "jr.live_plot('/ti_mmwave/radar_scan_pcl/:data.x:data.y', PointCloud2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!rqt_plot /poser"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
